[package]
name = "RustAPI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
path = "src/server.rs" 


[dependencies]
actix-web = "4"
dotenv = "0.15.0"
tokio = "1.34.0"
tokio-postgres = "0.7.10"
